---OPTIONS--
INSERT INTO TOPTION VALUES (1, 'male');
INSERT INTO TOPTION VALUES (2, 'female');
INSERT INTO TOPTION VALUES (3, 'other');

INSERT INTO TOPTION VALUES (4, 'not important');
INSERT INTO TOPTION VALUES (5, 'important');
INSERT INTO TOPTION VALUES (6, 'very important');

INSERT INTO TOPTION VALUES (7, 'yes');
INSERT INTO TOPTION VALUES (8, 'sometimes');
INSERT INTO TOPTION VALUES (9, 'no');

INSERT INTO TOPTION VALUES (10, 'maybe');
--yes
--no

INSERT INTO TOPTION VALUES (11, 'never married');
INSERT INTO TOPTION VALUES (12, 'separated');
INSERT INTO TOPTION VALUES (13, 'divorced');
INSERT INTO TOPTION VALUES (14, 'widowed');

INSERT INTO TOPTION VALUES (15, 'never');
INSERT INTO TOPTION VALUES (16, 'once or twice a year');
INSERT INTO TOPTION VALUES (17, 'once or twice a month');
INSERT INTO TOPTION VALUES (18, 'once or twice a week');
INSERT INTO TOPTION VALUES (19, 'I\''m drinking my 3rd mojito now, and it\''s only 11am');

INSERT INTO TOPTION VALUES (20, 'once or twice a year');
INSERT INTO TOPTION VALUES (21, 'socially');
INSERT INTO TOPTION VALUES (22, 'frequently');
--never

INSERT INTO TOPTION VALUES (23, 'I\''m completely opposed');
INSERT INTO TOPTION VALUES (24, 'I\''ve been know to dabble');
INSERT INTO TOPTION VALUES (25, 'drugs enrich my life');

INSERT INTO TOPTION VALUES (26, 'friendship');
INSERT INTO TOPTION VALUES (27, 'a hot date');
INSERT INTO TOPTION VALUES (28, 'an affair');
INSERT INTO TOPTION VALUES (29, 'a short-term relationship');
INSERT INTO TOPTION VALUES (30, 'a long-term relationship');

INSERT INTO TOPTION VALUES (31, 'probably');
INSERT INTO TOPTION VALUES (32, 'eventually');
--yes
--no
-- 7, 31, 32, 9

INSERT INTO TOPTION VALUES (33, 'cohabitation');
INSERT INTO TOPTION VALUES (34, 'separate flat / room in the same building');
INSERT INTO TOPTION VALUES (35, 'separate flats in the same area');
INSERT INTO TOPTION VALUES (36, 'weekend-relationship');
INSERT INTO TOPTION VALUES (37, 'long distance relationship');

INSERT INTO TOPTION VALUES (38, 'most of the time');
INSERT INTO TOPTION VALUES (39, 'often');
INSERT INTO TOPTION VALUES (40, 'rarely');
INSERT INTO TOPTION VALUES (41, 'not at all');
--sometimes

INSERT INTO TOPTION VALUES (42, 'a few times a day');
INSERT INTO TOPTION VALUES (43, 'daily');
INSERT INTO TOPTION VALUES (44, 'a few times a week');
INSERT INTO TOPTION VALUES (45, 'a few times a month');
-- rarely

INSERT INTO TOPTION VALUES (46, 'less than a day');
INSERT INTO TOPTION VALUES (47, 'one day');
INSERT INTO TOPTION VALUES (48, 'one week');
INSERT INTO TOPTION VALUES (49, 'one month');
INSERT INTO TOPTION VALUES (50, 'I\''d never do something like that');

INSERT INTO TOPTION VALUES (51, 'every day');
INSERT INTO TOPTION VALUES (52, 'a few times a week');
INSERT INTO TOPTION VALUES (53, 'once a week');
INSERT INTO TOPTION VALUES (54, 'every two weeks');
INSERT INTO TOPTION VALUES (55, 'infrequently');
--rarely

INSERT INTO TOPTION VALUES (56, 'Yes, definitely!');
INSERT INTO TOPTION VALUES (57, 'Now and then - why not?');
INSERT INTO TOPTION VALUES (58, 'I\''d give it a try');
INSERT INTO TOPTION VALUES (59, 'I don\''t know');
INSERT INTO TOPTION VALUES (60, 'Absolutely not');

INSERT INTO TOPTION VALUES (61, 'always');
--often
--sometimes
--rarely
--never

---QUESTIONS--
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (1, 'What is your gender?', 'HARDFACT', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (2, 'How important is the gender of your partner?', 'HARDFACT', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (3, 'How important is the age of your partner to you?', 'HARDFACT', 'SINGLE_CHOICE_CONDITIONAL');

INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (4, 'Do any children under the age of 18 live with you?', 'HARDFACT', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (5, 'How should your potential partner respond to this question?', 'LIFESTYLE', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (6, 'Could you imagine having children with your potential partner?', 'LIFESTYLE', 'SINGLE_CHOICE');

INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (7, 'How should your potential partner respond to this question?', 'LIFESTYLE', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (8, 'What is your marital status?', 'HARDFACT', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (9, 'How often do your drink alcohol?', 'LIFESTYLE', 'SINGLE_CHOICE');

INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (10, 'How often do you smoke?', 'LIFESTYLE', 'SINGLE_CHOICE');

INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (11, 'What is your attitude towards drugs?', 'LIFESTYLE', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (12, 'You are looking for...', 'LIFESTYLE', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (13, 'Would you like to get married?', 'LIFESTYLE', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (14, 'What is your ideal living arrangement?', 'LIFESTYLE', 'SINGLE_CHOICE');

INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (15, 'Do you enjoy spending time alone?', 'INTROVERSION', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (16, 'When you\''re alone, do you get lonely quickly?', 'INTROVERSION', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (17, 'Do you enjoy going on holiday by yourself?', 'INTROVERSION', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (18, 'I consciously take \''me time\''', 'INTROVERSION', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (19, 'Should one keep little secrets from one\''s partner?', 'INTROVERSION', 'SINGLE_CHOICE');

INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (20, 'How often do you think about sex?', 'PASSION', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (21, 'If you were alone on a desert island, how long would you last before pleasuring yourself?', 'PASSION', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (22, 'How often would you like to have sex with your prospective partner?', 'PASSION', 'SINGLE_CHOICE');

INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (23, 'Do you like trying out new things in bed and experimenting?', 'PASSION', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (24, 'I can enjoy sex without love', 'PASSION', 'SINGLE_CHOICE');
INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (25, 'For me, a stable relationship is a prerequisite for really good sex', 'PASSION', 'SINGLE_CHOICE');

INSERT INTO TQUESTION (ID, QUESTION_TEXT, CATEGORY, OPTION_TYPE) VALUES (140, 'What age should your potential partner be?', 'HARDFACT', 'NUMBER_RANGE');

--QUESTION_OPTION--
INSERT INTO TQUESTION_OPTIONS VALUES(1, 1);
INSERT INTO TQUESTION_OPTIONS VALUES(1, 2);
INSERT INTO TQUESTION_OPTIONS VALUES(1, 3);

INSERT INTO TQUESTION_OPTIONS VALUES(2, 4);
INSERT INTO TQUESTION_OPTIONS VALUES(2, 5);
INSERT INTO TQUESTION_OPTIONS VALUES(2, 6);

INSERT INTO TQUESTION_OPTIONS VALUES(3, 4);
INSERT INTO TQUESTION_OPTIONS VALUES(3, 5);
INSERT INTO TQUESTION_OPTIONS VALUES(3, 6);

INSERT INTO TQUESTION_OPTIONS VALUES(4, 7);
INSERT INTO TQUESTION_OPTIONS VALUES(4, 8);
INSERT INTO TQUESTION_OPTIONS VALUES(4, 9);

INSERT INTO TQUESTION_OPTIONS VALUES(5, 7);
INSERT INTO TQUESTION_OPTIONS VALUES(5, 8);
INSERT INTO TQUESTION_OPTIONS VALUES(5, 9);

INSERT INTO TQUESTION_OPTIONS VALUES(6, 7);
INSERT INTO TQUESTION_OPTIONS VALUES(6, 10);
INSERT INTO TQUESTION_OPTIONS VALUES(6, 9);

INSERT INTO TQUESTION_OPTIONS VALUES(7, 7);
INSERT INTO TQUESTION_OPTIONS VALUES(7, 10);
INSERT INTO TQUESTION_OPTIONS VALUES(7, 9);

INSERT INTO TQUESTION_OPTIONS VALUES(8, 11);
INSERT INTO TQUESTION_OPTIONS VALUES(8, 12);
INSERT INTO TQUESTION_OPTIONS VALUES(8, 13);
INSERT INTO TQUESTION_OPTIONS VALUES(8, 14);

INSERT INTO TQUESTION_OPTIONS VALUES(9, 15);
INSERT INTO TQUESTION_OPTIONS VALUES(9, 16);
INSERT INTO TQUESTION_OPTIONS VALUES(9, 17);
INSERT INTO TQUESTION_OPTIONS VALUES(9, 18);
INSERT INTO TQUESTION_OPTIONS VALUES(9, 19);

INSERT INTO TQUESTION_OPTIONS VALUES(10, 15);
INSERT INTO TQUESTION_OPTIONS VALUES(10, 20);
INSERT INTO TQUESTION_OPTIONS VALUES(10, 21);
INSERT INTO TQUESTION_OPTIONS VALUES(10, 22);

INSERT INTO TQUESTION_OPTIONS VALUES(11, 23);
INSERT INTO TQUESTION_OPTIONS VALUES(11, 24);
INSERT INTO TQUESTION_OPTIONS VALUES(11, 25);

INSERT INTO TQUESTION_OPTIONS VALUES(12, 26);
INSERT INTO TQUESTION_OPTIONS VALUES(12, 27);
INSERT INTO TQUESTION_OPTIONS VALUES(12, 28);
INSERT INTO TQUESTION_OPTIONS VALUES(12, 29);
INSERT INTO TQUESTION_OPTIONS VALUES(12, 30);

INSERT INTO TQUESTION_OPTIONS VALUES(13, 7);
INSERT INTO TQUESTION_OPTIONS VALUES(13, 31);
INSERT INTO TQUESTION_OPTIONS VALUES(13, 32);
INSERT INTO TQUESTION_OPTIONS VALUES(13, 9);

INSERT INTO TQUESTION_OPTIONS VALUES(14, 33);
INSERT INTO TQUESTION_OPTIONS VALUES(14, 34);
INSERT INTO TQUESTION_OPTIONS VALUES(14, 35);
INSERT INTO TQUESTION_OPTIONS VALUES(14, 36);
INSERT INTO TQUESTION_OPTIONS VALUES(14, 37);
-- 38,39,8,40,21
INSERT INTO TQUESTION_OPTIONS VALUES(15, 38);
INSERT INTO TQUESTION_OPTIONS VALUES(15, 39);
INSERT INTO TQUESTION_OPTIONS VALUES(15, 8);
INSERT INTO TQUESTION_OPTIONS VALUES(15, 40);
INSERT INTO TQUESTION_OPTIONS VALUES(15, 41);

INSERT INTO TQUESTION_OPTIONS VALUES(16, 38);
INSERT INTO TQUESTION_OPTIONS VALUES(16, 39);
INSERT INTO TQUESTION_OPTIONS VALUES(16, 8);
INSERT INTO TQUESTION_OPTIONS VALUES(16, 40);
INSERT INTO TQUESTION_OPTIONS VALUES(16, 41);

INSERT INTO TQUESTION_OPTIONS VALUES(17, 38);
INSERT INTO TQUESTION_OPTIONS VALUES(17, 39);
INSERT INTO TQUESTION_OPTIONS VALUES(17, 8);
INSERT INTO TQUESTION_OPTIONS VALUES(17, 40);
INSERT INTO TQUESTION_OPTIONS VALUES(17, 41);

INSERT INTO TQUESTION_OPTIONS VALUES(18, 38);
INSERT INTO TQUESTION_OPTIONS VALUES(18, 39);
INSERT INTO TQUESTION_OPTIONS VALUES(18, 8);
INSERT INTO TQUESTION_OPTIONS VALUES(18, 40);
INSERT INTO TQUESTION_OPTIONS VALUES(18, 41);

INSERT INTO TQUESTION_OPTIONS VALUES(19, 38);
INSERT INTO TQUESTION_OPTIONS VALUES(19, 39);
INSERT INTO TQUESTION_OPTIONS VALUES(19, 8);
INSERT INTO TQUESTION_OPTIONS VALUES(19, 40);
INSERT INTO TQUESTION_OPTIONS VALUES(19, 41);
-- 42,43,44,45,40
INSERT INTO TQUESTION_OPTIONS VALUES(20, 42);
INSERT INTO TQUESTION_OPTIONS VALUES(20, 43);
INSERT INTO TQUESTION_OPTIONS VALUES(20, 44);
INSERT INTO TQUESTION_OPTIONS VALUES(20, 45);
INSERT INTO TQUESTION_OPTIONS VALUES(20, 40);

INSERT INTO TQUESTION_OPTIONS VALUES(21, 46);
INSERT INTO TQUESTION_OPTIONS VALUES(21, 47);
INSERT INTO TQUESTION_OPTIONS VALUES(21, 48);
INSERT INTO TQUESTION_OPTIONS VALUES(21, 49);
INSERT INTO TQUESTION_OPTIONS VALUES(21, 50);

INSERT INTO TQUESTION_OPTIONS VALUES(22, 51);
INSERT INTO TQUESTION_OPTIONS VALUES(22, 52);
INSERT INTO TQUESTION_OPTIONS VALUES(22, 53);
INSERT INTO TQUESTION_OPTIONS VALUES(22, 54);
INSERT INTO TQUESTION_OPTIONS VALUES(22, 55);
INSERT INTO TQUESTION_OPTIONS VALUES(22, 40);

INSERT INTO TQUESTION_OPTIONS VALUES(23, 56);
INSERT INTO TQUESTION_OPTIONS VALUES(23, 57);
INSERT INTO TQUESTION_OPTIONS VALUES(23, 58);
INSERT INTO TQUESTION_OPTIONS VALUES(23, 59);
INSERT INTO TQUESTION_OPTIONS VALUES(23, 60);
-- 61, 49, 8, 40, 15
INSERT INTO TQUESTION_OPTIONS VALUES(24, 61);
INSERT INTO TQUESTION_OPTIONS VALUES(24, 49);
INSERT INTO TQUESTION_OPTIONS VALUES(24, 8);
INSERT INTO TQUESTION_OPTIONS VALUES(24, 40);
INSERT INTO TQUESTION_OPTIONS VALUES(24, 15);

INSERT INTO TQUESTION_OPTIONS VALUES(25, 61);
INSERT INTO TQUESTION_OPTIONS VALUES(25, 49);
INSERT INTO TQUESTION_OPTIONS VALUES(25, 8);
INSERT INTO TQUESTION_OPTIONS VALUES(25, 40);
INSERT INTO TQUESTION_OPTIONS VALUES(25, 15);
