DROP TABLE IF EXISTS TANSWER;
CREATE TABLE TANSWER (
	ID BIGINT NOT NULL,
	QID BIGINT NOT NULL,
	OID BIGINT,
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TOPTION;
CREATE TABLE TOPTION (  
	ID BIGINT NOT NULL,  
	TEXT VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TQUESTION;
CREATE TABLE TQUESTION (
	ID BIGINT NOT NULL,
	QUESTION_TEXT VARCHAR(255) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	OPTION_TYPE VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);


